### ISSUE TITLE
Apply agreed project structure

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#143]
Right now, KitchenSink does not conform to the project structure agreed in https://github.com/Starcounter/Guidelines/blob/master/project_structure.md.

Please adapt the project structure to it.

**Comment by warpech** [comment]
This should be done after https://github.com/Starcounter/KitchenSink/tree/polymer2 is merged to `develop`

**Comment by PatrykSzwer** [comment]
Should this be done only at 2.4 branch, only at master branch or on both? (right now merging either `master` to `master-2.4` or `master-2.4` to `master` would cause unwanted changes and errors).

**Comment by PatrykSzwer** [comment]
Closing as done (thankfully)
