### ISSUE TITLE
Tests problem with Window.Maximize()

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#190]
After my last changes in https://github.com/Starcounter/KitchenSink/pull/189, KitchenSink tests pass, but have rather ridiculous double call to `Window.Maximize()`:

https://github.com/Starcounter/KitchenSink/blob/607cfcdd9cd66d2fa90481db2f186572aeda50b9/test/KitchenSink.Tests/Utilities/WebDriverManager.cs#L36

https://github.com/Starcounter/KitchenSink/blob/607cfcdd9cd66d2fa90481db2f186572aeda50b9/test/KitchenSink.Tests/Test/BaseTest.cs#L54

The problem that I fixed was connected to the fact that Firefox 55 does not correctly maximize a window: https://github.com/mozilla/geckodriver/issues/900

We need to find a solution that does not involve calling `Maximize()` twice.

In order to have rather predictable tests, maybe we should set a specific window size, instead of relying on maximizing it?

```
Driver.Manage().Window.SetPosition(new Point(0,0));
Driver.Manage().Window.SetSize(new Dimension(1024,768));
```

**Comment by PatrykSzwer** [comment]
I've actually removed this one, unnecessary Maximize call, and locally, everything seems working. I've created PR #191  for this, We will see if tests on teamcity will fail or not.

**Comment by PatrykSzwer** [comment]
I've replaced Manage().Window calls with options argument. I think It's most elegant and most of all reliable solution.

**Comment by PatrykSzwer** [comment]
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/KitchenSink/releases/tag/2.0.0
- published in the App Warehouse
- blogged at https://starcounter.io/kitchensink-2-0-0-released-includes-34-common-ui-patterns/
