### ISSUE TITLE
Polymer 2.x version only works in Chrome

### ISSUE THREAD

**Issue by alshakero** [Starcounter/KitchenSink#196]
This issue is to share my progress and maybe get some help. I'm still investigating the issue, but if you'd like to help and/or curious about our progress with Polymer 2.0, you can follow these steps to have a running Polymer 2.0 KS app:

1. Clone [SysUpgrade#Polymer2-WCv1](https://github.com/Starcounter/SysUpgrade/tree/Polymer2-WCv1). This is an easier way to have [`starcounter-include#Polymer2-friendly`](https://github.com/Starcounter/Starcounter-include/tree/Polymer2-friendly) and [`imported-template#Polymer2-friendly`](https://github.com/Juicy/imported-template/tree/Polymer2-friendly)` in Starcounter.
2. Clone [KitchenSink#polymer2](https://github.com/Starcounter/KitchenSink/tree/polymer2).

Run SysUpgrade + KS and you're set. 

Helpfull notes:
1. A telling phenomenon is that the app works in Chrome even when I remove both polyfills, WCv1 + `d-r-e`, and this means Chrome gives too much room for error and testing with it is hardly inclusive. 
2. All interesting files that you can modify on the fly to are in `Sysupgade/src/SysUpgrade/wwwroot/sys`.

**Comment by warpech** [comment]
This will be fixed after `d-r-e` is removed from Starcounter 2.4.

Closing as solved by other means.

**Comment by warpech** [comment]
The remaining problem is tracked here https://github.com/Starcounter/starcounter-include/issues/69
