### ISSUE TITLE
Builds with warnings in Starcounter 2.3.1.x

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#201]
Current `master` branch uses APIs that are deprecated in Starcounter 2.3.1.x.

![image](https://user-images.githubusercontent.com/566463/32854169-0944ee90-ca3e-11e7-85c7-c76244dec755.png)

@un-tone can you pls fix this?

**Comment by un-tone** [comment]
Closing as done

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/KitchenSink/releases/tag/2.0.0
- published in the App Warehouse
- blogged at https://starcounter.io/kitchensink-2-0-0-released-includes-34-common-ui-patterns/
