### ISSUE TITLE
Hosted demo of KitchenSink

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#205]
We should have hosted demo of KitchenSink (e.g. at <http://kitchensink.starcounter.io/kitchensink>) that always uses the current Starcounter RC and KitchenSink. It should be deployed automatically after a successful build of http://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_KitchenSink_Develop.

I discussed this on 2017-11-21 with @LarsTjernstrom and he said it would improve his workflow if he could check KitchenSink without running it locally.

@ubbeK could you please take this?

**Comment by LarsTjernstrom** [comment]
If we should promote live demos of polymer components, we should definatly
change the name!
What's in my Kitchen sink is garbage and we don't consider a Web UI tool
demonstration to be garbage, Or?


[image: photo]

<https://www.facebook.com/StarcounterDB/>
<https://www.linkedin.com/company/starcounterdb>
<https://twitter.com/StarcounterDB>

 *Lars Tjernström *| *Software architect *
+46 70 668 08 87
<http://t.sidekickopen55.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW-gY64zKlYVQBb2Y56dStCf2-JMT-02?si=X-SIG-APPLE-NOKEY&pi=8F71530B-5836-4470-86D0-463AA94B2205&t=http%3A%2F%2Ft%2Esidekickopen55%2Ecom%2Fe1t%2Fc%2F5%2Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%2DgY64zKlYVQBb2Y56dStCf2%2DJMT%2D02%3Fsi%3DX%2DSIG%2DAPPLE%2DNOKEY%26pi%3D933EB8FF%2DBDA5%2D4644%2DB3FF%2D9117AF12413F%26t%3Dhttp%253A%252F%252Ft%252Esidekickopen54%252Ecom%252Fe1t%252Fc%252F5%252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%252DgY64zKlYVQBb2Y56dStCf2%252DJMT%252D02%253Fsi%253DX%2DSIG%2DAPPLE%2DNOKEY%2526pi%253DE9813137%252DA95D%252D4994%252D9892%252D39A47DCF486F%2526t%253Dhttp%25253A%25252F%25252Ft%25252Esidekickopen51%25252Ecom%25252Fe1t%25252Fc%25252F5%25252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%25252DgY64zKlYVQBb2Y56dStCf2%25252DJMT%25252D02%25253Fsi%25253DX%25252DSIG%25252DAPPLE%25252DNOKEY%252526pi%25253DE60A8C49%25252D695E%25252D4E4D%25252D9ED7%25252D2044EB4D773E%252526t%25253Dhttp%2525253A%2525252F%2525252Ft%2525252Esidekickopen42%2525252Ecom%2525252Fe1t%2525252Fc%2525252F5%2525252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%2525252DgY64zKlYVQBb2Y56dStCf2%2525252DJMT%2525252D02%2525253Fsi%2525253DX%25252DSIG%25252DAPPLE%25252DNOKEY%25252526pi%2525253DAAB9D957%2525252DC78B%2525252D41D0%2525252DACB9%2525252D73F20BB47B41%25252526t%2525253Dhttp%252525253A%252525252F%252525252Ft%252525252Esidekickopen42%252525252Ecom%252525252Fe1t%252525252Fc%252525252F5%252525252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%252525252DgY64zKlYVQBb2Y56dStCf2%252525252DJMT%252525252D02%252525253Fsi%252525253DX%252525252DSIG%252525252DAPPLE%252525252DNOKEY%2525252526pi%252525253DE894EC10%252525252DD5B5%252525252D44A6%252525252DA816%252525252D4D46AFBA1CD3%2525252526t%252525253Dhttp%25252525253A%25252525252F%25252525252Ft%25252525252Esidekickopen42%25252525252Ecom%25252525252Fe1t%25252525252Fc%25252525252F5%25252525252Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qStn2W2zW%25252525252DgY64zKlYVQBb2Y56dStCf2%25252525252DJMT%25252525252D02%25252525253Fsi%2525>
 | lars.tjernstrom@starcounter.com
www.starcounter.com | www.starcounter.io
Hovslagargatan 3, 111 48 Stockholm, Sweden

**Comment by warpech** [comment]
"Kitchen Sink" is a standard name for demo of UI component collections: https://www.google.pl/search?q=kitchensink+demo

**Comment by alshakero** [comment]
I'd appreciate that a lot. I needed a live SC app many times.

**Comment by ubbeK** [comment]
This issue has been added to UrbanStar project but is not planned to be implemented any time soon.

**Comment by ubbeK** [comment]
@warpech @LarsTjernstrom So we want a publicly accessible version of latest Starcounter RC version + Latest Kitchensink. Will there be a need for other apps to be tested like this in the future?

**Comment by ubbeK** [comment]
This is more or less how I would go about this.

In short:

- Create new AWS EC2 instance
- Trigger from TeamCity
- Scripts on AWS EC2 instance server
- Configure DNS records
- Misc

## Create new AWS EC2 instance
I would like to have a new AWS EC2 instance server for this which will host the Starcounter server. I have talked to @LarsTjernstrom about `App-teams` future desire of verifying their `Solution` or `Set of apps` on each new Starcounter version and it is safe to say that they will also benefit for such a cloud server. Hence the cost of such server will be reasonable if we combine the two to use the same instance. I also want to add that `IT-support` will implement `IT phase 2` which will include an `Active Directory` and I have asked them to integrate our AWS instances there. 

## Trigger from TeamCity
I have not found any built-in functionality on TeamCity which can trigger an HTTP GET request, but it should not be a problem with doing this from the command line of the [Kitchensink](https://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_KitchenSink_Develop)-build in question.

## Scripts on AWS EC2 instance server
We will need some sort of server which receives the HTTP GET request from the TeamCity build, I would probably use some lightweight python option. This request should execute any necessary script to set up the entire Starcounter server. Please make sure that any useful information from TeamCity is passed on through this request.

The script should, in short, do the following:

- Do any prerequisites before continuing:
    - Authentication
    - Determine what should be updated / executed
    - Kill Starcounter servers / apps safely
- Download installer (latest or what is specified through the HTTP request)
- Install the installer through command line: `Starcounter-<Channel>-<Version>-Setup.exe Silent productionmode unattended`
- pull latest `Kitchensink` from Github
- compile `Kitchensink`
- Deploy `Kitchensink` executables.
    
Please consider that there will be multiple different databases on this EC2 instance, so make sure these scripts have some intelligence, especially when upgrading to new Starcounter version and what apps that should be redeployed. That is why I strongly recommend using https://github.com/Starcounter/cbwatchdog/releases/tag/v1.1.0 for this.

On a side note, the part of installing new Starcounter version, compiling and deploying an App, is a part of this issue: https://github.com/Starcounter/AdminTrack/issues/340
    
## Configure DNS records
`starcounter.io`, `starcounter.com` and `starcounter.org` have all been bought through [nameisp.com](https://www.nameisp.com/en/) but have their nameservers pointing to [CloudFlare](https://www.cloudflare.com/).

- NameServer1: connie.ns.cloudflare.com
- NameServer2: vick.ns.cloudflare.com
    
So whatever domain we use, the `DNS record` has to be configured there. And as such, I strongly suggest to set up an SSL certificate using `CloudFlare` as well. All credentials needed for this may be found in `Nybrokajen.kdbx`. 
    
## Misc
**Any newly created credentials have to be placed in `Nybrokajen.kdbx`.**

It is time to create a private GitHub repository which centralizes all kind of scripts that we use all over. And for backup and traceability purposes as well. It should look like the following so we keep it structured. 

```
/<NameOfNewScriptRepo>
    README.md
    /<NameOfEC2Instance>
        README.md
        <Scripts>
```

Make sure that the root `README.md` describes what the repository is used for in general and that each folder has its own `README.md` which describes what that particular part is used for (when, where, what, why and how).

This means that all scripts from `Scripts on AWS EC2 instance server` should be located in `/<NameOfEC2Instance>`-folder.
    - cbwatchdog configurations
    - execution scripts
    - preferably also the source of the python server itself

And as such, this repo would be pulled from GitHub as well in the `Scripts on AWS EC2 instance server` section of this issue.
    
Lastly, it is time to create a new Starcounter GitHub user which has access to this repository as it is too sensitive to use `Starcounter-GoodTimes` everywhere.

cc @warpech

**Comment by warpech** [comment]
@ubbeK thanks so much for the write-up! I was thinking that someone from the @Starcounter/webplatformteam can do that, but now I can see it looks freaking complex to do it right. So I think we will have to wait until you have resources for that.

Btw there is one config that attempted some simple deployment (but thats to Warehouse, not to AWS): http://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_KitchenSink_Deploy.

I think that a need for CI will grow, so it is good to have a common script for that.

In the past, we've used to have one more deployment script for deploying SweOffshore on AWS. I believe it was made by @joozek78.

**Comment by mmnosek** [comment]
Side question: shouldn't we do the same kind of continuous delivery with `inside.starcounter.com`? Anyway, it should be described as a way to go continuous delivery with Stacounter afterwards. And be the reference point to how we simplify this process in the process, iteratively.

**Comment by ubbeK** [comment]
We should definetly take a step toward continous delivery. Regard updating apps we will probably do this through the warehouse but this issue also takes the starcounter installation into acount as well.

**Comment by warpech** [comment]
I have launched KitchenSink 2.0.0 in Starcounter 2.4 on an AWS machine "Hosted KitchenSink". This is the smallest EC2 instance (`t2.micro`). The credentials are in RDG.

https://kitchensink.starcounter.io/

Currently, there is no continuous delivery of it. It is installed manually.

**Comment by miyconst** [comment]
The live demo link should be available somewhere to discover, readme, starcounter.io, maybe other places as well.

**Comment by joozek78** [comment]
A few notes about the plan:
> I have not found any built-in functionality on TeamCity which can trigger an HTTP GET request

It's super easy to create a [meta-runner](https://confluence.jetbrains.com/display/TCD10/Working+with+Meta-Runner) to achieve this

> pull latest Kitchensink from Github
> compile KitchenSink

Since we trigger it from the KitchenSink build, isn't it easier and better to use the artifacts just created?
If we are cloudflare enterprise customers, then we can use [Client Certificate Authentication](https://blog.cloudflare.com/introducing-tls-client-auth/) to secure TeamCity - Instance communication

**Comment by warpech** [comment]
The following is needed before this issue can be closed:

- [ ] Add instructions about deploying `kitchensink.starcounter.io` to CONTRIBUTING.md
- [ ] Update the screenshot in README.md with the text "Try KitchenSink live", move it to the top of README.md
- [ ] Change the default branch of this repo to `master-2.4` so that the screenshot is visible at https://github.com/Starcounter/KitchenSink

Future enhancements (separate issues):

- [Add information about the current version of the app](https://github.com/Starcounter/KitchenSink/issues/284)

**Comment by tomalec** [comment]
Don't we need a Blending Provider app, to remove the outmost margin?

**Comment by PatrykSzwer** [comment]
> Don't we need a Blending Provider app, to remove the outmost margin?

Yes, currently we're not setting margin anywhere in our design system (to not force it to user, just leave default `8px` one given by browser), instead, we're using custom composition of topbar layout to override it.

**Comment by PatrykSzwer** [comment]
>I think we are Starcounter/underwear.css:underwear.unminified.css@master#L578

It's because of that (comes from normalize): https://github.com/Starcounter/underwear.css/blob/master/underwear.unminified.css#L26

**Comment by warpech** [comment]
Closing as done. Continuous delivery can be established later. It is tracked in https://github.com/Starcounter/KitchenSink/issues/292
