### ISSUE TITLE
Uses old `<link is="palindrom-redirect">`

### ISSUE THREAD

**Issue by alshakero** [Starcounter/KitchenSink#220]
Should be upgraded to `<palindrom-redirect />`

@PatrykSzwer would you like to take that?

**Comment by PatrykSzwer** [comment]
Should this be applied for 2.4 only?

**Comment by alshakero** [comment]
@warpech @tomalec do you think 

```html
<palindrom-redirect slot="kitchensink/redirect-link-redirect" is="palindrom-redirect" url="{{model.RedirectUrl$}}">
	<link slot="kitchensink/redirect-link-redirect" is="palindrom-redirect" url="{{model.RedirectUrl$}}">
</palindrom-redirect>
```

Is a good idea to make it hybrid?

**Comment by tomalec** [comment]
1. I'd not add a `slot` attr to is, as it is non-visual element,
2. Slot in nested element is not needed anyhow,
3. Do we need a hybrid version? If so, let's do it but add a code comment that it's just a fallback for 2.3

**Comment by alshakero** [comment]
It's not neccassry but the less diversion between `master` and `master-2.4` the better.

**Comment by tomalec** [comment]
On the other hand, the  less hybrid versions we have to maintain the agiler we are and the cleaner the code is.

**Comment by alshakero** [comment]
Oh, you're right! I missed that! East or west we'll need to have different bower version for `palindrom-client`. It isn't like `dom-bind`. 

So I change my mind. I think this issue only applies to 2.4.

**Comment by tomalec** [comment]
Also, we already maintain separate `master-2.4 branch`

**Comment by tomalec** [comment]
fixed in https://github.com/Starcounter/KitchenSink/pull/221

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/KitchenSink/releases/tag/2.0.0
- published in the App Warehouse
- blogged at https://starcounter.io/kitchensink-2-0-0-released-includes-34-common-ui-patterns/
