### ISSUE TITLE
Upgrade juicy-select to the current version

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#225]
Upgrade `juicy-select` with Bower to the current version https://github.com/Juicy/juicy-select/releases/tag/1.1.0

**Comment by kegor** [comment]
Closed as it is fixed in the #226.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/KitchenSink/releases/tag/2.0.0
- published in the App Warehouse
- blogged at https://starcounter.io/kitchensink-2-0-0-released-includes-34-common-ui-patterns/
