### ISSUE TITLE
Failing tests on Firefox in Starcoutner 2.3

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#227]
There are failing tests on `master` branch after https://github.com/Starcounter/KitchenSink/pull/223 was merged to `master-2.4` and then `master-2.4` to `master`. That was the kind of change that was supposed to be done with [`ours` merge strategy](https://git-scm.com/docs/merge-strategies) on the `master` branch.

@PatrykSzwer can you please revert https://github.com/Starcounter/KitchenSink/pull/223 on the `master` branch? It should only be kept on `master-2.4`

**Comment by PatrykSzwer** [comment]
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/KitchenSink/releases/tag/2.0.0
- published in the App Warehouse
- blogged at https://starcounter.io/kitchensink-2-0-0-released-includes-34-common-ui-patterns/
