### ISSUE TITLE
Misspelling: target="_black"

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/KitchenSink#230]
[https://github.com/Starcounter/KitchenSink/blob/master-2.4/src/KitchenSink/wwwroot/KitchenSink/UrlPage.html#L11](url)

**Comment by Mackiovello** [comment]
Good catch! The link seems to be bad, here's a working one: https://github.com/Starcounter/KitchenSink/blob/17957236f496b5d28ce76e2d22106b7a189ef143/src/KitchenSink/wwwroot/KitchenSink/UrlPage.html#L11

**Comment by warpech** [comment]
Thanks for reporting. @kegor can you pls fix?

**Comment by kegor** [comment]
Closed as fixed in #232.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/KitchenSink/releases/tag/2.0.0
- published in the App Warehouse
- blogged at https://starcounter.io/kitchensink-2-0-0-released-includes-34-common-ui-patterns/
