### ISSUE TITLE
Solution builds with warnings

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#231]
Similar to: https://github.com/Starcounter/Blending/issues/41

The solution builds with few deprecation warnings. @kegor could you please look up what are the current methods to use and upgrade the code?

Please make the PR to `master-2.4` but the changes should build with Starcounter 2.4 and 2.3.1 (we will check on TeamCity).

**Comment by kegor** [comment]
@PatrykSzwer pointed that the reason in unused and perhaps forgotten reference to Simplified.Data.Model (without installed nuget-package for 2.4 versions). So this reference was just removed. Now there are no warnings on build.

**Comment by PatrykSzwer** [comment]
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/KitchenSink/releases/tag/2.0.0
- published in the App Warehouse
- blogged at https://starcounter.io/kitchensink-2-0-0-released-includes-34-common-ui-patterns/
