### ISSUE TITLE
There are 2 kitchenSink apps in warehouse

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/KitchenSink#234]
Right now in the warehouse, We can find two KitchenSink apps:
![image](https://user-images.githubusercontent.com/25042256/34989536-28fa69da-fac3-11e7-9de0-0f25768da037.png)
I'm 99% sure that the first one can be deleted, and the second one should be added to the shop, to be visible for users, but I would like to have some confirmation about that.
@warpech Could You confirm that I can delete `Kitchen Sink` from the warehouse and add `KitchenSink` to one of the shops?

(BTW I've added recent releases to the `KitchenSink` one)

**Comment by warpech** [comment]
> @warpech Could You confirm that I can delete Kitchen Sink from the warehouse and add KitchenSink to one of the shops?

Yes, please do so

**Comment by PatrykSzwer** [comment]
Already done, closing.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/KitchenSink/releases/tag/2.0.0
- published in the App Warehouse
- blogged at https://starcounter.io/kitchensink-2-0-0-released-includes-34-common-ui-patterns/
