### ISSUE TITLE
KitchenSink.Tests targetFramework=4.5.2, while for KitchenSink is 4.6.2

### ISSUE THREAD

**Issue by kegor** [Starcounter/KitchenSink#235]
While exploring KitchenSink.Tests project I found the unexpected detail, that despite the fact that KitchenSink itself has targetFramework=4.6.2 tests still has targetFramework=4.5.2.

I had issue [Use .NET Framework 4.6.1 for apps](https://github.com/Starcounter/Home/issues/347) in a near past, and there is looks reasonable to change targetFramework version to 4.6.2 following the main project?

@warpech are you agree?

**Comment by warpech** [comment]
Yes, please do that. Thanks for suggesting.

**Comment by kegor** [comment]
Closed because fixed in #236.
