### ISSUE TITLE
Switch KitchenSink from Bootstrap to Underwear.css + Uniform.css

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#238]

**Comment by PatrykSzwer** [comment]
I've created branch `underwear-2.4` which contains all changes from `underwear` branch and It's compatible with newest SC 2.4.0. It also contains newest version of underwear from @alshakero. For now there are manually added files for uniform, underwear and normalizer, after release of  StarcounterClientFiles 3.0.0-rc.1 with Underwear and Uniform I'll remove those.

**Comment by alshakero** [comment]
@PatrykSzwer StarcounterClientFiles 3.0.0-rc.1 is released.

**Comment by PatrykSzwer** [comment]
I've updated `underwear-2.4` branch, by removing all local files that are provided now with StarcounterClientFiles (I've left uniform for now, for test purposes since @alshakero needs to do some additional changes).

**Comment by warpech** [comment]
This looks really good! I hope we can merge by the end of the week.

@PatrykSzwer the tests are failing with the [`underwear-2.4`](http://localhost:8080/KitchenSink/MainPage) branch. Is that expected?

@PatrykSzwer can you make a PR of `underwear-2.4` to `master-2.4`?

@alshakero BreadcrumbPage and other pages try to import `/sys/uniform/uniform.css`, which gives 404 with StarcounterClientFiles 3.0.0-rc.1. Pls fix.

@alshakero On the TablePage, there is no right border on the table.

I made a few fixes to the branch. In https://github.com/Starcounter/KitchenSink/commit/650d5beca8f9a74295edaa742cb5e95b39110649 I showed how I imagine the styles being moved from the common `style.css` file to Shadow DOM of particular views. I think it needs to be repeated for ALL pages. That will let us delete `style.css`. @alshakero do you agree? Can you do that?

**Comment by andwah** [comment]
Any reason why the `Datagrid `and `Table` does not have the same styling?

**DataGrid**

![image](https://user-images.githubusercontent.com/2656996/35383010-5571b144-01c1-11e8-851d-81200c93eac4.png)

**Table**

![image](https://user-images.githubusercontent.com/2656996/35383023-5fd856a6-01c1-11e8-97b2-ad23a6c329b0.png)

Would be nice if they had the same look'n'feeling.

**Comment by andwah** [comment]
DatePicker looks strange (using chrome Version 63.0.3239.132)

![image](https://user-images.githubusercontent.com/2656996/35383206-e8295a32-01c1-11e8-94aa-7004fa9f7530.png)

**Comment by andwah** [comment]
Components uses different Theme color's

**Toggle button**
![image](https://user-images.githubusercontent.com/2656996/35383402-815e7bb0-01c2-11e8-932a-f6638440e92f.png)

**Breadcrumbs**
![image](https://user-images.githubusercontent.com/2656996/35383460-ad1305fa-01c2-11e8-8b41-b9fb37ea51b1.png)

**Radio Buttons**
![image](https://user-images.githubusercontent.com/2656996/35383539-daefd796-01c2-11e8-90f8-4e5a29f99d39.png)

**Radio Lists**
![image](https://user-images.githubusercontent.com/2656996/35383578-f2701994-01c2-11e8-9faf-42987c7c097a.png)

**Validation**
![image](https://user-images.githubusercontent.com/2656996/35383623-0ec9539e-01c3-11e8-9483-a7a03a055db6.png)

**Comment by warpech** [comment]
>Any reason why the Datagridand Table does not have the same styling?

Datagrid is a `hot-table` custom element that has encapsulated look and feel. It might not be pretty but it can't simply be styled by Underwear, which is in light DOM.

> DatePicker looks strange (using chrome Version 63.0.3239.132)

Thanks, @PatrykSzwer has a fix for this AFAIK.

> Components uses different Theme color's

These components are Paper components which need an additional compatibility layer that is beyond the scope of Underwear.css. Track https://github.com/Starcounter/Blending/issues/52 for the future solution.

---

Thanks for the review!

A question from me: `'Last Name' should not be empty` looks bad. Do we have some desired style for this that can be added to Uniform.css?

**Comment by alshakero** [comment]
> A question from me: 'Last Name' should not be empty looks bad. Do we have some desired style for this that can be added to Uniform.css?

We can make something similar to https://getbootstrap.com/docs/3.3/components/#alerts. They seem quite easy to make.

**Comment by andwah** [comment]
> A question from me: 'Last Name' should not be empty looks bad. Do we have some desired style for this that can be added to Uniform.css?

I think for the moment we just need change the color the red theme color.




> We can make something similar to https://getbootstrap.com/docs/3.3/components/#alerts. They seem quite easy to make.

The problem with "alerts" that they will "push" down or overlay elements below. 
I think a small text below the field in the space beetween components. is the best way at the moment as long it does not move any other elemens .

**Comment by PatrykSzwer** [comment]
> DatePicker looks strange (using chrome Version 63.0.3239.132)

@andwah solution for that should be here: https://github.com/Starcounter/KitchenSink/pull/240
After this PR will be merged, I will pull those changes to underwear branch and see how It will look with our framework.

**Comment by PatrykSzwer** [comment]
DatePicker should look good right now, all changes from #240 are merged.

**Comment by alshakero** [comment]
https://github.com/Starcounter/KitchenSink/pull/240 seems to be merged to `master-2.4`, Shouldn't new changes be merged to `underwear-2.4` branch from now on until we merge?

**Comment by warpech** [comment]
Closing as done in https://github.com/Starcounter/KitchenSink/pull/241
