### ISSUE TITLE
Using ninject with KitchenSink

### ISSUE THREAD

**Issue by aloscha** [Starcounter/KitchenSink#24]
I think @warpech you could write to blog or some else, that SC support Ninject (unfortunatelly not in constructor) but in main it works - https://github.com/StarcounterSamples/KitchenSink/tree/Ninject_%2324

Also need to add waver.ignore file with Ninject.dll to use that.

**Comment by per-samuelsson** [comment]
> ...  that SC support Ninject (**unfortunatelly not in constructor**)

Could you clarify that? I want to know what it is we don't support, so we can try to find ways to support that in future versions.

**Comment by warpech** [comment]
A blind guess looking at https://github.com/Starcounter/KitchenSink/commit/a00b7e1794446ef5256376992e323d01d62f4ce6 - maybe what @aloscha means is the limitation of TypedJson which disallows to overload a Json constructor?

**Comment by joozek78** [comment]
I think he meant exactly that. We spoke about that topic

**Comment by per-samuelsson** [comment]
Ah, thanks @warpech and @joozek78, I thought there was a problem with database classes not supporting some certain constructor. Now I know.

**Comment by warpech** [comment]
Archiving. C# dependency injection is not a commonly required pattern nor it is a UI problem so I don't see how it fits in KitchenSink.
