### ISSUE TITLE
Pagination does not look as intended

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#247]
This is how pagination looks in KitchenSink `underwear-2.4` branch (https://github.com/Starcounter/KitchenSink/pull/241/commits/f53910a003d493e8cd88dd80f83c04fc80927a93) with StarcounterClientFiles 3.0.0-rc.5:

![image](https://user-images.githubusercontent.com/566463/36193892-e31835b2-1167-11e8-9f1b-f68e7a85a3ea.png)

This is how it should look according to the design:

![image](https://user-images.githubusercontent.com/566463/36193975-3882ef74-1168-11e8-9ca8-22c46dd2f4a1.png)

Problems:

1. The active page should be marked by a border. @tomalec can something be done about it?
2. The word "Next" has bad margin
3. The disabled page link ("Previous") looks weird. @andwah can you add a disabled link to the https://drive.google.com/drive/u/0/folders/1YnNLer6FP6AgEGQM--ma_7i1mUkMwfHf

**Comment by andwah** [comment]
TeamDrive updated with this design

![image](https://user-images.githubusercontent.com/2656996/36195799-f4f5bf64-116e-11e8-856b-719706185243.png)

**Comment by warpech** [comment]
@PatrykSzwer can you please work on this?

**Comment by andwah** [comment]
@PatrykSzwer How can i help you?

**Comment by tomalec** [comment]
> 1. The active page should be marked by a border. @tomalec can something be done about it?

Done:
https://github.com/Starcounter/KitchenSink/pull/255

**Comment by warpech** [comment]
Closing as done

**Comment by tomalec** [comment]
@warpech  Why do you think it's done?
![obraz](https://user-images.githubusercontent.com/17435/36780329-f2616942-1c72-11e8-9eb3-4376a231ea30.png)

I'd say, two last points still stands
> 2. The word "Next" has bad margin
> 3. The disabled page link ("Previous") looks weird. @andwah can you add a disabled link to the

**Comment by warpech** [comment]
Because all the remaining issues should be fixed in Uniform.css, not KitchenSink.

Firefox issue is tracked elsewhere: https://github.com/Starcounter/uniform.css/issues/56

> The word "Next" has bad margin

I added this to https://github.com/Starcounter/uniform.css/issues/52

> The disabled page link ("Previous") looks weird. @andwah can you add a disabled link to the

This is tracked elsewhere: https://github.com/Starcounter/uniform.css/issues/52
