### ISSUE TITLE
Clicking next page in pagination advances two pages not one

### ISSUE THREAD

**Issue by tomalec** [Starcounter/KitchenSink#248]
##### Browsers affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari

**Comment by warpech** [comment]
I am assigning it to you @alshakero, because from @PatrykSzwer's prestudy it seems that it is a client-side issue.

**Comment by alshakero** [comment]
PR in https://github.com/Starcounter/KitchenSink/pull/277

**Comment by alshakero** [comment]
Closing as fixed in #277.
