### ISSUE TITLE
Checkbox does not look as desired

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#253]
Moved from https://github.com/Starcounter/KitchenSink/pull/241#issuecomment-366739193

----

@alshakero  writes:

One minor but pet-peevy issue. `CheckboxPage` has this:

```html
<input slot="kitchensink/checkbox-input" type="checkbox" checked="{{model.DrivingLicense$::change}}">

<div slot="kitchensink/checkbox-license-label">{{model.DrivingLicenseReaction}}</div>
```

Which results in this:
![image](https://user-images.githubusercontent.com/17054134/36387146-693a3986-1598-11e8-81d1-684d7c193ee2.png)

This is due to `uni-label-control`. @tomalec.

Here is the desired look 
![image](https://user-images.githubusercontent.com/17054134/36393806-748496c4-15b1-11e8-9b87-e6e5a6168554.png)

**Comment by warpech** [comment]
@alshakero you mean the positioning of the checkbox's label, right?

**Comment by alshakero** [comment]
> @alshakero you mean the positioning of the checkbox's label, right?

Exactly.

**Comment by tomalec** [comment]
Do you think it should use the same structure `<div class="uni-label-control"><slot name="forcheckbox"/><slot name="forlabel"/></div>`? I'd rather use different class/structure for that.

**Comment by alshakero** [comment]
Good idea. I agree with this. It's simpler, does the job and quite easy to understand (for users).

**Comment by warpech** [comment]
@PatrykSzwer and @andwah can you work on it tomorrow? Add an example of using a checkbox with a label to Uniform.css, including the demo page.

**Comment by andwah** [comment]
@PatrykSzwer How can i help you?.

**Comment by PatrykSzwer** [comment]
We discussed this and agreed that we should add possibility to choose the site where label goes, so we should have:

- uni-label-control (I'm not sure if control word is needed here, maybe we could think about some shorter name? But from another side we decided to not change api anymore if I'm correct) by default should be on top of the input text field and on the right side of the checbox input (if its possible to detect, if not then just on top by default)
- uni-label-control-left - label on the left
- uni-label-control-right - label on the right
- uni-label-control-under - label under the input 

this will make possible to use the same class (uni-label-control) for all types of inputs and all types of label-something pair that needs another positioning.

**Comment by warpech** [comment]
`uni-label-control` has the following implementation:

```
.uni-label-control {
  display: grid;
  grid-template: "label";
  grid-gap: 1rem;
  align-items: baseline;
  justify-content: start;
  justify-items: start;
}
```

If we put all these values as variables, you could **configure** how to render `uni-label-control` while using the same CSS class, similarly how you configure the color of primary buttons. 

How does that sound?

**Comment by PatrykSzwer** [comment]
It sounds... tricky, because let's say you have 4 inputs on your view, and you want 2 of them to be control-left, one control default and one control-right. In this case you have to set variables for each of them in your composition. I think that would be really developer unfriendly. We can variablize part of the values, like grid-gap which I believe is the margin between label and input but I think it would be easier to use with proposed classes.

**Comment by warpech** [comment]
Ok I agree

**Comment by warpech** [comment]
Part 1 (in KS)

Remove the class uni-label-control and put the "You can drive" message in uni-alert-info.

Part 2 (in Uniform)

Implement uni-label-control-left, etc

**Comment by tomalec** [comment]
Speaking of names what do you think about `uni-label-pair`/`uni-label-couple` to emphasize coupling the label with any labelable element?

**Comment by PatrykSzwer** [comment]
Closing since the issue was fixed, but we should consider expending those uni-label-control classes as we spoke above.
