### ISSUE TITLE
Pagination buttons should not be <span>

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#263]
### Expected result

The pagination buttons should be a `<button>` or `<a href="">`, never `<span>`.

### Actual result

Currently the pagination buttons are done as `<span>`s.

**Comment by PatrykSzwer** [comment]
I'm afraid that this will need some changes in uniform/underwear also.
When using `button` tags, styles from underwear comming to a stage, and pagination starts looking like this:
![image](https://user-images.githubusercontent.com/25042256/37646130-11813666-2c29-11e8-8b48-23cd927f0908.png)
With `a` is better, but then disabled state styles are not handled properly (or at all):
![image](https://user-images.githubusercontent.com/25042256/37646164-2c05a4fe-2c29-11e8-898e-d2e9c49c863e.png)

**Comment by warpech** [comment]
This should be doable with `uni-flat-button`
