### ISSUE TITLE
Replace part of Assert's in tests to avoid flaky tests.

### ISSUE THREAD

**Issue by kegor** [Starcounter/KitchenSink#273]
As the continuation of this comment https://github.com/Starcounter/KitchenSink/pull/270#pullrequestreview-108530843.

### Steps to reproduce
Run build for KitchenSink in TeamCity.

### Expected result
All green tests.

### Actual result
There might be various failed tests in various runs.

##### Starcounter version 
Latest version available on TeamCity.

##### Involved apps' version
 - Starcounter/KitchenSink@2.2.0
 
##### Browsers affected
- [x] Chrome
- [x] Firefox

### Screenshot
![image](https://user-images.githubusercontent.com/17431807/38417785-5caf5ede-39a2-11e8-9581-5ffb6bbaf208.png)
![image](https://user-images.githubusercontent.com/17431807/38417830-89386ca2-39a2-11e8-830d-b96bfa8a5231.png)

**Comment by warpech** [comment]
Let's continue with this when https://github.com/Starcounter/KitchenSink/pull/274 is decided about.

**Comment by kegor** [comment]
Closed because last reasonable changes were merged in #297.
