### ISSUE TITLE
A new structure for the menu

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#275]
The current menu structure (Rendering, Server Push, User Input) is not optimal for developers looking for easy path to learn how to build complex UI with Starcounter.

We should come up with a new menu structure that might be inspired by the menu structure of:

- https://material.io/guidelines/
- https://www.lightningdesignsystem.com/getting-started/
- https://www.predix-ui.com/
- http://carbondesignsystem.com/
- https://cdn.vaadin.com/vaadin-lumo-styles/1.0.0-beta3/demo/
- https://ant.design/docs/spec/introduce
   - https://ant.design/docs/react/introduce
   - https://mobile.ant.design/docs/react/introduce

@PatrykSzwer this idea came from you, would you like to propose it?

**Comment by PatrykSzwer** [comment]
I think our new structure should contain at least 2 sections, one for the UI elements/components and one for our solutions for different functionalities.

Here are some of my propositions, we can vote for the best variant:

Names for the first `elements` section:
- **components**
- elements
- UI
- Look (only as a pair with feel)
- Style
- **Design**
- **Layout**
```
Names for the first `solutions` section:
- **Solutions**
- **Patterns**
- Brain
- Logic
- Usability
- feel (only as a pair with look)

I'll update this list if I came up with something new.

**Comment by warpech** [comment]
For me, the 1st section should be none of the above, but rather `Design` or sth like that. This section will be about Underwear, Uniform, etc.

The 2nd section would be `Components`.

The 3rd section would be `Solutions` or `How-to guides` to pair it with "How-to guides" of the [Docs](https://docs.starcounter.io/v/2.4/how-to-guides).

**Comment by tomalec** [comment]
I like the approach, suggested by @warpech of 
1. Design,
2. Components,
3. How-to guides (Solutions, could be confused with the solution of apps if the reader comes from Starcounter's Blending docs)

**Comment by PatrykSzwer** [comment]
But what would you like to add to `Design` section? I though we will "merge" Design and Components sections, to have uniform styling described under every component that can be styled by it. Unless you meant things like `uni-section` and `uni-card` described there, then I agree but I'm not sure how many of those will be there.

> For me, the 1st section should be none of the above, but rather Design or sth like that.

I suggested name `design` also :<

**Comment by warpech** [comment]
> I suggested name `Design` also :<

Sure, the credit goes to you, but what I mean is that it should be a section should be separate from `Components`.

Sample content:

- Design
  - Sections (.uni-section) and when to use them
  - Cards (.uni-card) and when to use them
  - Titles (.uni-title) and when to use them
  - Layout with left side navigation (.uni-layout-left-nav) and when to use it
- Components
  - Datepicker
  - Dropdown
  - Map
  - Pagination (.uni-pagination)
  - Text Input
- How to
  - Server push
  - Redirect

**Comment by PatrykSzwer** [comment]
>- Design
  - Sections (.uni-section) and when to use them
  - Cards (.uni-card) and when to use them
  - Titles (.uni-title) and when to use them
  - Layout with left side navigation (.uni-layout-left-nav) and when to use it
- Components
  - Datepicker
  - Dropdown
  - Map
  - Pagination (.uni-pagination)
  - Text Input
- How to
  - Server push
  - Redirect

I really like this structure, let's ask @tomalec for his final opinion and if everyone agrees then I'll implement this structure.

**Comment by tomalec** [comment]
I'd just add few thing more to the "design", like underwear and typography, just ot have a full showcase. Plus like a vision/principles/home page

- Home
- Design
  - Typograpy & native elements, (class-less markup) 
  - Sections (.uni-section) and when to use them
  - ...


Other than that, LGTM

**Comment by PatrykSzwer** [comment]
We decided with @warpech that this will be done in 2 iterations. In first I'll recreate menu structure and in a second we have to add those additional Design sections which do not exist right now.

**Comment by PatrykSzwer** [comment]
Closing, new issue for part 2: #283.
