### ISSUE TITLE
Fix warning about styling master document from HTML Import

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#282]
In Chrome, currently I get the following error:

![image](https://user-images.githubusercontent.com/566463/39001489-af0e547e-43f6-11e8-8012-1d48d8c7a677.png)

Solve this according to information in https://github.com/Starcounter/RebelsLounge/issues/222#issuecomment-382777626

**Comment by tomalec** [comment]
It is not `<link rel="preload" href="..uniform.css">` but `<link rel="stylesheet" href="/KitchenSink/style.css">` causing the problem. I'm reopening the issue, and taking it over.

**Comment by tomalec** [comment]
Closing as all changes on our end are done in https://github.com/Starcounter/KitchenSink/pull/309
Remaining packages that are still using the styles in imported docs, are:
- `font-roboto`,
- `vaadin-date-picker`,

`paper-elements` are still triggering the warning, even though they are not affected by the dropped support.
