### ISSUE TITLE
Redundant line in DatepickerPage

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#295]
@Mihaiii points out that this line https://github.com/Starcounter/KitchenSink/blob/79beb8e97c58facb0540aba5ebc500c1045c213a/src/KitchenSink/wwwroot/KitchenSink/DatepickerPage.html#L13 in DatepickerPage is redundant.

**Comment by tomalec** [comment]
PR is waiting for the review at https://github.com/Starcounter/KitchenSink/pull/298

**Comment by tomalec** [comment]
Fixed by
