### ISSUE TITLE
github-source-links element is in dependencies folder

### ISSUE THREAD

**Issue by tomalec** [Starcounter/KitchenSink#308]
All KitchenSink specific element should be kept in `src/KitchenSink/wwwroot/KitchenSink/*`.

BTW, If we are not planning to use it outside KitchenSink, I'd call it `kitchensink-gh-source-link`, to emphasize how specific to KitchenSink it is.

### Steps to reproduce
1. Prune bower dependencies folder `$ rm -rf src/KitchenSink/wwwroot/sys/`,
2. `bower install`

### Expected result
All dependencies should be updated, nothing should be lost

### Actual result
KitchenSink specific element - `github-source-links` is lost.

##### Starcounter version 
n/a
 
##### Browsers affected
n/a

//cc @alshakero Sorry that is something I missed at https://github.com/Starcounter/KitchenSink/pull/301 review

**Comment by warpech** [comment]
Fixed in https://github.com/Starcounter/KitchenSink/pull/317
