### ISSUE TITLE
kitchensink.starcounter.io is offline

### ISSUE THREAD

**Issue by warpech** [Starcounter/KitchenSink#310]
https://kitchensink.starcounter.io/ is offline. @PatrykSzwer could you pls bring it up?

**Comment by PatrykSzwer** [comment]
Sure! It's back online.

**Comment by warpech** [comment]
@miyconst an app deployed on AWS EC2 machine died with no reason and could not start without reinstalling. Is it something we should investigate? Where to look for clues?

Closing this issue for now.
