### ISSUE TITLE
Add smoke tests for opening up the starcounter-debug-aid

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/KitchenSink#73]
Add new Selenium regression tests which opens up the `starcounter-debug-aid` in order to ensure that the UI is working properly. There has been som uncertainties that it is working properly, see [this issue](https://github.com/Starcounter/starcounter-debug-aid/issues/41) for example.

**Comment by ubbeK** [comment]
@warpech @aloscha Help request from bi-weekly App meeting.

I am having problems with the `Interactions.Actions` class which builds a sequence of actions and performs it. I cannot get it to perform correctly, does anyone have any experiense with it?

See code [here](https://github.com/StarcounterSamples/KitchenSink/blob/debug-aid-test_issue-73/test/KitchenSink.Tests/Tests/StarcounterDebugAidTest.cs#L66)

I manage to get the test to pass by injecting JavaScript for Firefox but I think it is not the correct solution.

**Comment by aloscha** [comment]
For my first review:

1. Maybe instead of `Keys.Control` something which is come form Selenium `OpenQA.Selenium.Keys` (I don't know is for c# namespaces is the same)
2. After `KeyDown` should be `KeyUp` (also after sending keys)
3. If I remember well ( @warpech will know better), `SendKeys("§")` this is `section sign` and only occurs on mac in left keyboard corner.
![image](https://cloud.githubusercontent.com/assets/5141943/20286803/030e935e-aac9-11e6-91c8-b7a6975f1134.png)

On windows there are `tilde`. So maybe that tests pass on mac users. Basically this key have different values on each OS and `starcounter-debug-aid` is based on that.

**Comment by ubbeK** [comment]
@aloscha Thanks for the input. I will try it out tomorrow.

> If I remember well ( @warpech will know better), SendKeys("§") this is section sign and only occurs on mac in left keyboard corner. 

On Swedish keyboard layout the `section sign` appears on the same place as your picture. It has been discussed [here](https://github.com/Starcounter/starcounter-debug-aid/issues/41). I will have to make some workaround using the input about what keyboard language is currently used if possible.

**Comment by ubbeK** [comment]
Test now passes locally, will try to run them on TC.

Worth noting, The Build() and Perform() methods needs to be executed together on the same line in order do execute correctly (At least in Chrome).

```cs
//Works fine
new Actions(driver).KeyDown(Keys.Control).SendKeys("`").KeyUp(Keys.Control).Build().Perform();
```

```cs
//Works fine
Actions action = new Actions(driver).KeyDown(Keys.Control).SendKeys("`").KeyUp(Keys.Control);
action.Build().Perform();
```

```cs
//Will not work
Actions action = new Actions(driver).KeyDown(Keys.Control).SendKeys("`").KeyUp(Keys.Control);
action.Build()
action.Perform();
```
@aloscha Thanks for the help!

**Comment by warpech** [comment]
@alshakero will take over this. @ubbeK what's the status of this issue? Seems that the branch https://github.com/StarcounterApps/KitchenSink/tree/debug-aid-test_issue-73 was created but never merged.

**Comment by ubbeK** [comment]
It worked for chrome and edge if I remember correctly. Nothing was merged though, due to firefox.

**Comment by PatrykSzwer** [comment]
I think, since We're migrating to add-on solution this issue can be closed. Please reopen if You disagree.

**Comment by warpech** [comment]
Yes, in fact, we would not be able to test the Chrome Extension from the level of Selenium in a Starcounter app.
